---
title: "Bactmentha Database, mutations statistics"
author: "Lou BERGOGNE"
date: last-modified

format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
  html:
    theme: cerulean
    code-fold: true
    code-tools: true
    code-overflow: scroll

---

# Introduction

Some mutations informations about either the pathogen or the host proteins can be observed in BactMentha features tables. This code aims to provide some statistics about those mutations and particularly their effect on the interaction and their position (inside or outside the experimentally detected binding region or predictied interface).

# Methods

The classification of the features (binding reagions, mutations...) comes from the Search Ontology (<a href='https://www.ebi.ac.uk/ols4/'>https://www.ebi.ac.uk/ols4/</a>). The mimicint interfaces are provided by MimicINT tool.

## Mutations

Mutations can be characterized by their effect on the interaction the protein is involved in:<br>
 - **mutation**: A change in a sequence or structure in comparison to a reference entity due to a insertion, deletion or substitution event.<br>
 - **variant**: A natural change in a sequence or structure in comparison to a reference entity.<br>
 - **mutation increasing interaction**: Region of a molecule whose mutation or deletion increases significantly interaction strength or rate (in the case of interactions inferred from enzymatic reaction).<br>
 - **mutation increasing interaction strength**: Region of a molecule whose mutation or deletion increases significantly interaction strength.<br>
 - **mutation increasing interaction rate**: Region of a molecule whose mutation or deletion increases significantly interaction rate (in the case of interactions inferred from enzymatic reaction).<br>
 - **mutation decreasing interaction**: Region of a molecule whose mutation or deletion decreases significantly interaction strength or rate (in the case of interactions inferred from enzymatic reaction).<br>
 - **mutation decreasing interaction strength**: Region of a molecule whose mutation or deletion decreases significantly interaction strength.<br>
 - **mutatin decreasing interaction rate**: Region of a molecule whose mutation or deletion decreases significantly interaction rate (in the case of interactions inferred from enzymatic reaction).<br>
 - **mutation with no effect**: A change in a sequence or structure in comparison to a reference entity due to a insertion, deletion or substitution event that does not have any effect over an interaction when compared with the wild-type.<br>
 - **mutation causing an interaction**: A change in a sequence or structure in comparison to a reference entity due to a insertion, deletion or substitution event that enables an interaction when compared with the wild-type, which does not interact.<br>

 The mutations have been **categorized in five distinct categories** depending on their effect:<br>
 - **increasing the interaction** (+- strength / rate)<br>
 - **decreasing the interaction** (+- strength / rate)<br>
 - **causing the interaction**<br>
 - **no effect**<br>
 - **unknown effect** (mutation / variant)<br>

## Binding informations

Experimentally detected binding regions are defined in three distinct categories:<br>
- **binding-associated region**: A region of a molecule or a component of a complex identified as being involved in an interaction. This may or may not be a region of the molecule in direct contact with the interacting partner.<br>
- **sufficient binding region**: Binding will occur when this sequence range is present within a molecule or part of a molecule. This region will contain the direct binding region but may be longer.<br>
- **necessary binding region**: A sequence range within a molecule identified as being absolutely required for an interaction. The sequence may or may not be in direct physical contact with the interaction partner.<br>

**Interfaces** are domains or motifs. More informations can be found about those elements on Interpro (<a href='https://www.ebi.ac.uk/interpro/'>https://www.ebi.ac.uk/interpro/</a>) and ELM respectively (<a href='http://elm.eu.org/infos/news.html'>http://elm.eu.org/infos/news.html</a>).

## Mutations stats computation

In BactMentha, a single interaction can be referenced with distinct mnt_interaction_id (unique identifiers) depending on the method that was used to identify the interaction, the confidence score... In the features table, multiple features can be associated to the same interaction (mnt_interaction_id) when multiple binding associated regions or mutations have been identify during the experiment for example. Finally, distinct mnt_interaction_id that refer to the same interaction in terms of interacting partners (one pathogen protein and one host protein) that has been detected through different technics can be related to the same mimicint interface inferrence.<br>

For example:<br>
<tr> <td>pathogen protein</td> <td>host protein</td> <td></td> <td></td> <td></td> </tr>


# Resluts

```{python}
#| echo: false
#| label: stats tables import

import numpy as np
import pandas as pd

# Set stats folder
stats_folder = '/home/bergogne/Documents/BactMentha_DB/03_Script/04_Website/static/stats/'
table_A_name = '/stats_on_A_mutations.txt'
table_B_name = '/stats_on_B_mutations.txt'
table_total_name = '/total_stats_mutations.txt'

# human
human_tables = {'A' : pd.read_csv(stats_folder+'9606'+table_A_name, sep='\t', header = 0, index_col=0), 'B': pd.read_csv(stats_folder+'9606'+table_B_name, sep='\t', header = 0, index_col=0), 'total': pd.read_csv(stats_folder+'9606'+table_total_name, sep='\t', header = 0, index_col=0)}

# mouse
mouse_tables = {'A' : pd.read_csv(stats_folder+'10090'+table_A_name, sep='\t', header = 0, index_col=0), 'B': pd.read_csv(stats_folder+'10090'+table_B_name, sep='\t', header = 0, index_col=0), 'total': pd.read_csv(stats_folder+'10090'+table_total_name, sep='\t', header = 0, index_col=0)}

# rat
rat_tables = {'A' : pd.read_csv(stats_folder+'10116'+table_A_name, sep='\t', header = 0, index_col=0), 'B': pd.read_csv(stats_folder+'10116'+table_B_name, sep='\t', header = 0, index_col=0), 'total': pd.read_csv(stats_folder+'10116'+table_total_name, sep='\t', header = 0, index_col=0)}

# Set colors for the graphs:
pathogen_bar_color = "#cf9757"
host_bar_color = "#57cf77"
total_bar_color = "grey"
```


## Are mutations more found in the host or pathogen proteins ? Or do they have as much mutations as the other one ? Would it be the same upon all the host organisms ?

*Hypothesis : mutations appear randomly and are conserved or not. We can imagine that there will be as much conserved mutations in both categories of proteins (host and pathogens) and that it will be the same for all the host taxa.*

:::{.center}
```{python}
#| echo: false
#| fig-cap: "Figure 1: Number of mutations on the pathogens proteins, host proteins and total number of mutations in the interaction datasets per host taxon."

import matplotlib.pyplot as plt

# Get the wanted data:
human_A_mut = human_tables['A'].loc['total', 'total']
human_B_mut = human_tables['B'].loc['total', 'total']
human_T_mut = human_tables['total'].loc['total', 'total']
mouse_A_mut = mouse_tables['A'].loc['total', 'total']
mouse_B_mut = mouse_tables['B'].loc['total', 'total']
mouse_T_mut = mouse_tables['total'].loc['total', 'total']
rat_A_mut = rat_tables['A'].loc['total', 'total']
rat_B_mut = rat_tables['B'].loc['total', 'total']
rat_T_mut = rat_tables['total'].loc['total', 'total']
total_T = human_T_mut + mouse_T_mut + rat_T_mut
total_A = human_A_mut + mouse_A_mut + rat_A_mut
total_B = human_B_mut + mouse_B_mut + rat_B_mut

# fix the bars length for total, host and pathogen proteins:
total_bars = [total_T, human_T_mut, mouse_T_mut, rat_T_mut,]
A_bars = [total_A, human_A_mut, mouse_A_mut, rat_A_mut,]
B_bars = [total_B, human_B_mut, mouse_B_mut, rat_B_mut,]
bars_names = ['Total', 'Human', 'Mouse', 'Rat']

# fix the bar width
barWidth = 0.2

# fix the x positions of bars
first_stack = np.arange(len(total_bars))
second_stack = [x + barWidth for x in first_stack]
third_stack = [x + barWidth for x in second_stack]

# Create the 'Total mutations' bar
plt.bar(first_stack, total_bars, width = barWidth, color = total_bar_color, edgecolor = 'black', capsize=7, label='Total mutations')
# Create the 'Pathogen proteins mutations' bar
plt.bar(second_stack, A_bars, width = barWidth, color = pathogen_bar_color, edgecolor = 'black', capsize=7, label='Pathogen proteins mutations')
# Create the 'Host proteins mutations' bar
plt.bar(third_stack, B_bars, width = barWidth, color = host_bar_color, edgecolor = 'black', capsize=7, label='Host proteins mutations')

# General layout
plt.xticks([r + barWidth for r in range(len(first_stack))], bars_names)
plt.ylabel('Number of mutations')
plt.legend()

# Save the figure as a PNG file
plt.savefig('/home/bergogne/Documents/BactMentha_DB/03_Script/04_Website/static/stats/figures/figure_1.png', bbox_inches='tight', dpi=300)

# Show the plot with significance markers
plt.show()
```

We can see on the plot that for each host taxon, the number of mutations found in the pathogens proteins is likely the same as for the host proteins. We can see for the rat a bigger difference in the number of mutations in the pathogen and host proteins bars but it could be due to a lack of data for this specific taxon.

## Are some mutation types more present in the host or pathogens proteins than in the other organism ones ? What could that mean biologically ?

*Hypothesis : we can imagine we'll found more mutations related to the decrease of the interaction on the host side because evading the interaction with the pathogen would be an advantage. At the contrary we can think that more mutations related to the decrease of the interaction or causing the interaction will be found on the pathogens side.*


:::{.center}
```{python}
#| echo: false
#| fig-cap: "Figure 2: Categories of mutations for the host and pathogen proteins interaction datasets mutations, for (a) human, (b) mouse, (c) rat and (d) all the host taxa. There are 5 disinct categories of mutations: (cau) 'causing an interaction', (inc) 'increasing the interaction' (strength/rate), (dec) 'decreasing the interaction' (strength/rate), (noe) 'no effect' and (unk) 'unkown effect'."


import matplotlib.pyplot as plt

# Dict to store the data from the tables for the subplots
bars_dict = {
  "human_A": [human_tables['A'].loc['causing_int_mutations', 'total'],
              human_tables['A'].loc['increasing_int_mutations', 'total'],
              human_tables['A'].loc['decreasing_int_mutations', 'total'],
              human_tables['A'].loc['no_effect_mutations', 'total'],
              human_tables['A'].loc['unknown_effect_mutations', 'total']
  ],
  "human_B": [human_tables['B'].loc['causing_int_mutations', 'total'],
              human_tables['B'].loc['increasing_int_mutations', 'total'],
              human_tables['B'].loc['decreasing_int_mutations', 'total'],
              human_tables['B'].loc['no_effect_mutations', 'total'],
              human_tables['B'].loc['unknown_effect_mutations', 'total']
  ],
  "mouse_A": [mouse_tables['A'].loc['causing_int_mutations', 'total'],
              mouse_tables['A'].loc['increasing_int_mutations', 'total'],
              mouse_tables['A'].loc['decreasing_int_mutations', 'total'],
              mouse_tables['A'].loc['no_effect_mutations', 'total'],
              mouse_tables['A'].loc['unknown_effect_mutations', 'total']
  ],
  "mouse_B": [mouse_tables['B'].loc['causing_int_mutations', 'total'],
              mouse_tables['B'].loc['increasing_int_mutations', 'total'],
              mouse_tables['B'].loc['decreasing_int_mutations', 'total'],
              mouse_tables['B'].loc['no_effect_mutations', 'total'],
              mouse_tables['B'].loc['unknown_effect_mutations', 'total']
  ],
  "rat_A": [rat_tables['A'].loc['causing_int_mutations', 'total'],
              rat_tables['A'].loc['increasing_int_mutations', 'total'],
              rat_tables['A'].loc['decreasing_int_mutations', 'total'],
              rat_tables['A'].loc['no_effect_mutations', 'total'],
              rat_tables['A'].loc['unknown_effect_mutations', 'total']
  ],
  "rat_B": [rat_tables['B'].loc['causing_int_mutations', 'total'],
              rat_tables['B'].loc['increasing_int_mutations', 'total'],
              rat_tables['B'].loc['decreasing_int_mutations', 'total'],
              rat_tables['B'].loc['no_effect_mutations', 'total'],
              rat_tables['B'].loc['unknown_effect_mutations', 'total']
  ]
}

bars_dict['total_A'] = [
  bars_dict["human_A"][0] + bars_dict["mouse_A"][0] + bars_dict["rat_A"][0],
  bars_dict["human_A"][1] + bars_dict["mouse_A"][1] + bars_dict["rat_A"][1],
  bars_dict["human_A"][2] + bars_dict["mouse_A"][2] + bars_dict["rat_A"][2],
  bars_dict["human_A"][3] + bars_dict["mouse_A"][3] + bars_dict["rat_A"][3],
  bars_dict["human_A"][4] + bars_dict["mouse_A"][4] + bars_dict["rat_A"][4]
]
bars_dict['total_B'] = [
  bars_dict["human_B"][0] + bars_dict["mouse_B"][0] + bars_dict["rat_B"][0],
  bars_dict["human_B"][1] + bars_dict["mouse_B"][1] + bars_dict["rat_B"][1],
  bars_dict["human_B"][2] + bars_dict["mouse_B"][2] + bars_dict["rat_B"][2],
  bars_dict["human_B"][3] + bars_dict["mouse_B"][3] + bars_dict["rat_B"][3],
  bars_dict["human_B"][4] + bars_dict["mouse_B"][4] + bars_dict["rat_B"][4]
]

# Function to compute percentages for each category
def compute_percentages(mutation_counts):
    total = sum(mutation_counts)
    return [(count / total) * 100 for count in mutation_counts]

# Update the dictionary with percentage values
bars_dict_percent = {k: compute_percentages(v) for k, v in bars_dict.items()}

# Create a 2x2 grid of subplots
fig, sub_plots = plt.subplots(2, 2, figsize=(8, 8))
barWidth = 0.3

# Get common bar names for mutations categories
bars_names = ['cau', 'inc', 'dec', 'noe', 'unk']

# fix the x positions of bars
first_stack = np.arange(len(bars_dict["human_A"]))
second_stack = [x + barWidth for x in first_stack]

# Creates the subplots

# For human
sub_plots[0,0].bar(first_stack, bars_dict_percent['human_A'], width = barWidth, color = pathogen_bar_color, edgecolor = 'black', capsize=5, label='Pathogen proteins mutations')
sub_plots[0,0].bar(second_stack, bars_dict_percent['human_B'], width = barWidth, color = host_bar_color, edgecolor = 'black', capsize=5, label='Host proteins mutations')
sub_plots[0,0].set_xticks(first_stack + barWidth/2)
sub_plots[0,0].set_xticklabels(bars_names)
sub_plots[0,0].set_ylabel('Proportion of mutations (%)')
sub_plots[0,0].text(-0.2, 0.95 * max(bars_dict_percent['human_A'] + bars_dict_percent['human_B']), '(a)', fontsize=12, weight='bold')

# For mouse
sub_plots[0,1].bar(first_stack, bars_dict_percent['mouse_A'], width = barWidth, color = pathogen_bar_color, edgecolor = 'black', capsize=5, label='Pathogen proteins mutations')
sub_plots[0,1].bar(second_stack, bars_dict_percent['mouse_B'], width = barWidth, color = host_bar_color, edgecolor = 'black', capsize=5, label='Host proteins mutations')
sub_plots[0,1].set_xticks(first_stack + barWidth/2)
sub_plots[0,1].set_xticklabels(bars_names)
sub_plots[0,1].set_ylabel('Proportion of mutations (%)')
sub_plots[0,1].text(-0.2, 0.95 * max(bars_dict_percent['mouse_A'] + bars_dict_percent['mouse_B']), '(b)', fontsize=12, weight='bold')

# For rat
sub_plots[1,0].bar(first_stack, bars_dict_percent['rat_A'], width = barWidth, color = pathogen_bar_color, edgecolor = 'black', capsize=5, label='Pathogen proteins mutations')
sub_plots[1,0].bar(second_stack, bars_dict_percent['rat_B'], width = barWidth, color = host_bar_color, edgecolor = 'black', capsize=5, label='Host proteins mutations')
sub_plots[1,0].set_xticks(first_stack + barWidth/2)
sub_plots[1,0].set_xticklabels(bars_names)
sub_plots[1,0].set_ylabel('Proportion of mutations (%)')
sub_plots[1,0].text(-0.2, 0.95 * max(bars_dict_percent['rat_A'] + bars_dict_percent['rat_B']), '(c)', fontsize=12, weight='bold')

# For total
sub_plots[1,1].bar(first_stack, bars_dict_percent['total_A'], width = barWidth, color = pathogen_bar_color, edgecolor = 'black', capsize=5, label='Pathogen proteins mutations')
sub_plots[1,1].bar(second_stack, bars_dict_percent['total_B'], width = barWidth, color = host_bar_color, edgecolor = 'black', capsize=5, label='Host proteins mutations')
sub_plots[1,1].set_xticks(first_stack + barWidth/2)
sub_plots[1,1].set_xticklabels(bars_names)
sub_plots[1,1].set_ylabel('Proportion of mutations (%)')
sub_plots[1,1].text(-0.2, 0.95 * max(bars_dict_percent['total_A'] + bars_dict_percent['total_B']), '(d)', fontsize=12, weight='bold')

# Add a legend below the subplots
handles, labels = sub_plots[0,0].get_legend_handles_labels()  # Get handles and labels from the first subplot
fig.legend(handles, labels, loc='upper center', ncol=2, bbox_to_anchor=(0.5, 0.96))  # Centered legend

# Adjust layout to make room for the legend
plt.tight_layout(rect=[0, 0, 1, 0.93])  # Adjust the layout for the legend

# Save the figure as a PNG file
plt.savefig('/home/bergogne/Documents/BactMentha_DB/03_Script/04_Website/static/stats/figures/figure_2.png', bbox_inches='tight', dpi=300)

# Show the plot with significance markers
plt.show()
```

(a) We can see on the subplot (a) that most of the human pathogens interactors proteins have known mutations effects, with a majority of mutations decreasing the interaction (strength/rate). On the host proteins side, the mutations seem to also lead in the majority of the cases to a decrease of the interaction, but the mutations with no or unknown effect represent around 40% of the mutations detected on the host proteins and more than 20% of the human proteins mutations seem to increase the interaction (strength/rate) with their pathogen interactors.<br>
(b) On the second suplot, we can see that for the mouse, more than the half of the mutations detected on the pathogen proteins have an unkown or no effect on their interation with the mouse proteins. But here again, the majority of mutations on the pathogens proteins with a known effect are related to a decrease in the interactions with the host proteins. Comparing the mouse proteins mutations distribution to the human one, we can see more mutations without effect and less mutations associated to an increase of interaction (strength/rate).<br> 
(c) For the rat, the few detected interaction are all leading to a decreasing interaction rate or strength.<br>
(d) Finally, the distribution of the mutations effect depending on if they're found on the host protein or the pathogen protein suggests that the majority of the detected mutations are associated with a decrease of the interaction rate or strength, while a small part of those mutations can be realted to an increasing interaction (rate/strength) or have no effect, independant on the regardless of the organism to which they belong. However, the number of identified mutations vary among the host organisms. This lack of data could lead to a bias in the mutations effects distribution.<br>
The fact that many known mutations are leading to a weaker interaction was expected on the host protein side to avoid the interaction with the pathogen proteins. Maybe the fact that the pathogens proteins are also related to a lower interaction strength or rate could be due to a faster mutation rate of those organisms or to a specificity for some host organisms. <strong>It would be interesting to take an example of some pathogens that are known to interact with both the human and the mouse for which we have mutation data on the pathogen protein side. We could then try to identify some pathogen proteins interacting with both host proteins ans try to see if the mutation effect is different against one and the other.</strong>

## Are certain mutation effects found more in the binding regions and interfaces than out of them ? Is there a difference between host and pathogen proteins mutations localisation ?

*Hypothesis : we can imagine that the mutations that are impacting the interaction (positively or negatively) will be found in majority inside the binding regions and interfaces, while the mutations with no effect could be found more out of those regions. We can imagine that mutations or variant without description of the effect can equally be found inside or outside those regions. And finally, we could expect the results to be the same for the pathogen and the host proteins mutations.*

```{python}
#| echo: false

# Creates subtables by merging some parts of the tables:
localisations = ['in', 'out', 'nan']
categories = ['cau', 'inc', 'dec', 'noe', 'unk']

localisations = ['in', 'out', 'nan']
categories = ['cau', 'inc', 'dec', 'noe', 'unk']

human_A_loccat = [
  [human_tables['A'].loc['causing_int_mutations', 'in_BR_in_MI'] + \
    human_tables['A'].loc['causing_int_mutations', 'in_BR_out_MI'] + \
      human_tables['A'].loc['causing_int_mutations', 'out_BR_in_MI'] + \
        human_tables['A'].loc['causing_int_mutations', 'in_BR_no_MI'] + \
          human_tables['A'].loc['causing_int_mutations', 'no_BR_in_MI'],
  human_tables['A'].loc['causing_int_mutations', 'out_BR_out_MI'] + \
    human_tables['A'].loc['causing_int_mutations', 'out_BR_no_MI'] + \
      human_tables['A'].loc['causing_int_mutations', 'no_BR_out_MI'],
  human_tables['A'].loc['causing_int_mutations', 'no_BR_no_MI'],
  ],
  [human_tables['A'].loc['increasing_int_mutations', 'in_BR_in_MI'] + \
    human_tables['A'].loc['increasing_int_mutations', 'in_BR_out_MI'] + \
      human_tables['A'].loc['increasing_int_mutations', 'out_BR_in_MI'] + \
        human_tables['A'].loc['increasing_int_mutations', 'in_BR_no_MI'] + \
          human_tables['A'].loc['increasing_int_mutations', 'no_BR_in_MI'],
  human_tables['A'].loc['increasing_int_mutations', 'out_BR_out_MI'] + \
    human_tables['A'].loc['increasing_int_mutations', 'out_BR_no_MI'] + \
      human_tables['A'].loc['increasing_int_mutations', 'no_BR_out_MI'],
  human_tables['A'].loc['increasing_int_mutations', 'no_BR_no_MI'],
  ],
  [human_tables['A'].loc['decreasing_int_mutations', 'in_BR_in_MI'] + \
    human_tables['A'].loc['decreasing_int_mutations', 'in_BR_out_MI'] + \
      human_tables['A'].loc['decreasing_int_mutations', 'out_BR_in_MI'] + \
        human_tables['A'].loc['decreasing_int_mutations', 'in_BR_no_MI'] + \
          human_tables['A'].loc['decreasing_int_mutations', 'no_BR_in_MI'],
  human_tables['A'].loc['decreasing_int_mutations', 'out_BR_out_MI'] + \
    human_tables['A'].loc['decreasing_int_mutations', 'out_BR_no_MI'] + \
      human_tables['A'].loc['decreasing_int_mutations', 'no_BR_out_MI'],
  human_tables['A'].loc['decreasing_int_mutations', 'no_BR_no_MI'],
  ],
  [human_tables['A'].loc['no_effect_mutations', 'in_BR_in_MI'] + \
    human_tables['A'].loc['no_effect_mutations', 'in_BR_out_MI'] + \
      human_tables['A'].loc['no_effect_mutations', 'out_BR_in_MI'] + \
        human_tables['A'].loc['no_effect_mutations', 'in_BR_no_MI'] + \
          human_tables['A'].loc['no_effect_mutations', 'no_BR_in_MI'],
  human_tables['A'].loc['no_effect_mutations', 'out_BR_out_MI'] + \
    human_tables['A'].loc['no_effect_mutations', 'out_BR_no_MI'] + \
      human_tables['A'].loc['no_effect_mutations', 'no_BR_out_MI'],
  human_tables['A'].loc['no_effect_mutations', 'no_BR_no_MI'],
  ],
  [human_tables['A'].loc['unknown_effect_mutations', 'in_BR_in_MI'] + \
    human_tables['A'].loc['unknown_effect_mutations', 'in_BR_out_MI'] + \
      human_tables['A'].loc['unknown_effect_mutations', 'out_BR_in_MI'] + \
        human_tables['A'].loc['unknown_effect_mutations', 'in_BR_no_MI'] + \
          human_tables['A'].loc['unknown_effect_mutations', 'no_BR_in_MI'],
  human_tables['A'].loc['unknown_effect_mutations', 'out_BR_out_MI'] + \
    human_tables['A'].loc['unknown_effect_mutations', 'out_BR_no_MI'] + \
      human_tables['A'].loc['unknown_effect_mutations', 'no_BR_out_MI'],
  human_tables['A'].loc['unknown_effect_mutations', 'no_BR_no_MI'],
  ]
]
human_A_subtable = pd.DataFrame(human_A_loccat, columns=localisations, index=categories)

human_B_loccat = [
  [human_tables['B'].loc['causing_int_mutations', 'in_BR_in_MI'] + \
    human_tables['B'].loc['causing_int_mutations', 'in_BR_out_MI'] + \
      human_tables['B'].loc['causing_int_mutations', 'out_BR_in_MI'] + \
        human_tables['B'].loc['causing_int_mutations', 'in_BR_no_MI'] + \
          human_tables['B'].loc['causing_int_mutations', 'no_BR_in_MI'],
  human_tables['B'].loc['causing_int_mutations', 'out_BR_out_MI'] + \
    human_tables['B'].loc['causing_int_mutations', 'out_BR_no_MI'] + \
      human_tables['B'].loc['causing_int_mutations', 'no_BR_out_MI'],
  human_tables['B'].loc['causing_int_mutations', 'no_BR_no_MI'],
  ],
  [human_tables['B'].loc['increasing_int_mutations', 'in_BR_in_MI'] + \
    human_tables['B'].loc['increasing_int_mutations', 'in_BR_out_MI'] + \
      human_tables['B'].loc['increasing_int_mutations', 'out_BR_in_MI'] + \
        human_tables['B'].loc['increasing_int_mutations', 'in_BR_no_MI'] + \
          human_tables['B'].loc['increasing_int_mutations', 'no_BR_in_MI'],
  human_tables['B'].loc['increasing_int_mutations', 'out_BR_out_MI'] + \
    human_tables['B'].loc['increasing_int_mutations', 'out_BR_no_MI'] + \
      human_tables['B'].loc['increasing_int_mutations', 'no_BR_out_MI'],
  human_tables['B'].loc['increasing_int_mutations', 'no_BR_no_MI'],
  ],
  [human_tables['B'].loc['decreasing_int_mutations', 'in_BR_in_MI'] + \
    human_tables['B'].loc['decreasing_int_mutations', 'in_BR_out_MI'] + \
      human_tables['B'].loc['decreasing_int_mutations', 'out_BR_in_MI'] + \
        human_tables['B'].loc['decreasing_int_mutations', 'in_BR_no_MI'] + \
          human_tables['B'].loc['decreasing_int_mutations', 'no_BR_in_MI'],
  human_tables['B'].loc['decreasing_int_mutations', 'out_BR_out_MI'] + \
    human_tables['B'].loc['decreasing_int_mutations', 'out_BR_no_MI'] + \
      human_tables['B'].loc['decreasing_int_mutations', 'no_BR_out_MI'],
  human_tables['B'].loc['decreasing_int_mutations', 'no_BR_no_MI'],
  ],
  [human_tables['B'].loc['no_effect_mutations', 'in_BR_in_MI'] + \
    human_tables['B'].loc['no_effect_mutations', 'in_BR_out_MI'] + \
      human_tables['B'].loc['no_effect_mutations', 'out_BR_in_MI'] + \
        human_tables['B'].loc['no_effect_mutations', 'in_BR_no_MI'] + \
          human_tables['B'].loc['no_effect_mutations', 'no_BR_in_MI'],
  human_tables['B'].loc['no_effect_mutations', 'out_BR_out_MI'] + \
    human_tables['B'].loc['no_effect_mutations', 'out_BR_no_MI'] + \
      human_tables['B'].loc['no_effect_mutations', 'no_BR_out_MI'],
  human_tables['B'].loc['no_effect_mutations', 'no_BR_no_MI'],
  ],
  [human_tables['B'].loc['unknown_effect_mutations', 'in_BR_in_MI'] + \
    human_tables['B'].loc['unknown_effect_mutations', 'in_BR_out_MI'] + \
      human_tables['B'].loc['unknown_effect_mutations', 'out_BR_in_MI'] + \
        human_tables['B'].loc['unknown_effect_mutations', 'in_BR_no_MI'] + \
          human_tables['B'].loc['unknown_effect_mutations', 'no_BR_in_MI'],
  human_tables['B'].loc['unknown_effect_mutations', 'out_BR_out_MI'] + \
    human_tables['B'].loc['unknown_effect_mutations', 'out_BR_no_MI'] + \
      human_tables['B'].loc['unknown_effect_mutations', 'no_BR_out_MI'],
  human_tables['B'].loc['unknown_effect_mutations', 'no_BR_no_MI'],
  ]
]
human_B_subtable = pd.DataFrame(human_B_loccat, columns=localisations, index=categories)

mouse_A_loccat = [
  [mouse_tables['A'].loc['causing_int_mutations', 'in_BR_no_MI'] ,
   mouse_tables['A'].loc['causing_int_mutations', 'out_BR_no_MI'],
   mouse_tables['A'].loc['causing_int_mutations', 'no_BR_no_MI'],
  ],
  [mouse_tables['A'].loc['increasing_int_mutations', 'in_BR_no_MI'] ,
   mouse_tables['A'].loc['increasing_int_mutations', 'out_BR_no_MI'],
   mouse_tables['A'].loc['increasing_int_mutations', 'no_BR_no_MI'],
  ],
  [mouse_tables['A'].loc['decreasing_int_mutations', 'in_BR_no_MI'] ,
   mouse_tables['A'].loc['decreasing_int_mutations', 'out_BR_no_MI'],
   mouse_tables['A'].loc['decreasing_int_mutations', 'no_BR_no_MI'],
  ],
  [mouse_tables['A'].loc['no_effect_mutations', 'in_BR_no_MI'] ,
   mouse_tables['A'].loc['no_effect_mutations', 'out_BR_no_MI'],
   mouse_tables['A'].loc['no_effect_mutations', 'no_BR_no_MI'],
  ],
  [mouse_tables['A'].loc['unknown_effect_mutations', 'in_BR_no_MI'] ,
   mouse_tables['A'].loc['unknown_effect_mutations', 'out_BR_no_MI'],
   mouse_tables['A'].loc['unknown_effect_mutations', 'no_BR_no_MI'],
  ]
]
mouse_A_subtable = pd.DataFrame(mouse_A_loccat, columns=localisations, index=categories)


mouse_B_loccat = [
  [mouse_tables['B'].loc['causing_int_mutations', 'in_BR_no_MI'] ,
   mouse_tables['B'].loc['causing_int_mutations', 'out_BR_no_MI'],
   mouse_tables['B'].loc['causing_int_mutations', 'no_BR_no_MI'],
  ],
  [mouse_tables['B'].loc['increasing_int_mutations', 'in_BR_no_MI'] ,
   mouse_tables['B'].loc['increasing_int_mutations', 'out_BR_no_MI'],
   mouse_tables['B'].loc['increasing_int_mutations', 'no_BR_no_MI'],
  ],
  [mouse_tables['B'].loc['decreasing_int_mutations', 'in_BR_no_MI'] ,
   mouse_tables['B'].loc['decreasing_int_mutations', 'out_BR_no_MI'],
   mouse_tables['B'].loc['decreasing_int_mutations', 'no_BR_no_MI'],
  ],
  [mouse_tables['B'].loc['no_effect_mutations', 'in_BR_no_MI'] ,
   mouse_tables['B'].loc['no_effect_mutations', 'out_BR_no_MI'],
   mouse_tables['B'].loc['no_effect_mutations', 'no_BR_no_MI'],
  ],
  [mouse_tables['B'].loc['unknown_effect_mutations', 'in_BR_no_MI'] ,
   mouse_tables['B'].loc['unknown_effect_mutations', 'out_BR_no_MI'],
   mouse_tables['B'].loc['unknown_effect_mutations', 'no_BR_no_MI'],
  ]
]
mouse_B_subtable = pd.DataFrame(mouse_B_loccat, columns=localisations, index=categories)

rat_A_loccat = [
  [rat_tables['A'].loc['causing_int_mutations', 'in_BR_no_MI'] ,
   rat_tables['A'].loc['causing_int_mutations', 'out_BR_no_MI'],
   rat_tables['A'].loc['causing_int_mutations', 'no_BR_no_MI'],
  ],
  [rat_tables['A'].loc['increasing_int_mutations', 'in_BR_no_MI'] ,
   rat_tables['A'].loc['increasing_int_mutations', 'out_BR_no_MI'],
   rat_tables['A'].loc['increasing_int_mutations', 'no_BR_no_MI'],
  ],
  [rat_tables['A'].loc['decreasing_int_mutations', 'in_BR_no_MI'] ,
   rat_tables['A'].loc['decreasing_int_mutations', 'out_BR_no_MI'],
   rat_tables['A'].loc['decreasing_int_mutations', 'no_BR_no_MI'],
  ],
  [rat_tables['A'].loc['no_effect_mutations', 'in_BR_no_MI'] ,
   rat_tables['A'].loc['no_effect_mutations', 'out_BR_no_MI'],
   rat_tables['A'].loc['no_effect_mutations', 'no_BR_no_MI'],
  ],
  [rat_tables['A'].loc['unknown_effect_mutations', 'in_BR_no_MI'] ,
   rat_tables['A'].loc['unknown_effect_mutations', 'out_BR_no_MI'],
   rat_tables['A'].loc['unknown_effect_mutations', 'no_BR_no_MI'],
  ]
]
rat_A_subtable = pd.DataFrame(rat_A_loccat, columns=localisations, index=categories)


rat_B_loccat = [
  [rat_tables['B'].loc['causing_int_mutations', 'in_BR_no_MI'] ,
   rat_tables['B'].loc['causing_int_mutations', 'out_BR_no_MI'],
   rat_tables['B'].loc['causing_int_mutations', 'no_BR_no_MI'],
  ],
  [rat_tables['B'].loc['increasing_int_mutations', 'in_BR_no_MI'] ,
   rat_tables['B'].loc['increasing_int_mutations', 'out_BR_no_MI'],
   rat_tables['B'].loc['increasing_int_mutations', 'no_BR_no_MI'],
  ],
  [rat_tables['B'].loc['decreasing_int_mutations', 'in_BR_no_MI'] ,
   rat_tables['B'].loc['decreasing_int_mutations', 'out_BR_no_MI'],
   rat_tables['B'].loc['decreasing_int_mutations', 'no_BR_no_MI'],
  ],
  [rat_tables['B'].loc['no_effect_mutations', 'in_BR_no_MI'] ,
   rat_tables['B'].loc['no_effect_mutations', 'out_BR_no_MI'],
   rat_tables['B'].loc['no_effect_mutations', 'no_BR_no_MI'],
  ],
  [rat_tables['B'].loc['unknown_effect_mutations', 'in_BR_no_MI'] ,
   rat_tables['B'].loc['unknown_effect_mutations', 'out_BR_no_MI'],
   rat_tables['B'].loc['unknown_effect_mutations', 'no_BR_no_MI'],
  ]
]
rat_B_subtable = pd.DataFrame(rat_B_loccat, columns=localisations, index=categories)

```


:::{.center}
```{python}
#| echo: false
#| fig-cap: "Figure 3: Localisation of mutations for the host and pathogen proteins interaction datasets mutations, for (a) human, (b) mouse, (c) rat and (d) all the host taxa, depending on the effect of the mutation. There are 5 disinct categories of mutations: (cau) 'causing an interaction', (inc) 'increasing the interaction' (strength/rate), (dec) 'decreasing the interaction' (strength/rate), (noe) 'no effect' and (unk) 'unkown effect'. The possible location are : (in) 'inside the binding regions or the mimicint interfaces', (out) 'out of them', or (nan) 'no binding region or interface data'."

import seaborn as sns
import matplotlib.colors as mcolors

# Create custom color palettes
def create_custom_cmap(colors):
    return mcolors.LinearSegmentedColormap.from_list("custom_cmap", colors)

# Define color shades
greens = create_custom_cmap(['#ddf0e2', host_bar_color])  # Light to dark green
oranges = create_custom_cmap(['#f0e7dd', pathogen_bar_color])  # Light to dark orange

# Creating a figure for the 6 heatmaps
fig, axes = plt.subplots(2, 3, figsize=(8, 8), gridspec_kw={'height_ratios': [1, 1], 'width_ratios': [1, 1, 1]})

# Heatmap plotting function
def plot_heatmap(data, ax, cmap='Greens', cbar=False, ylabel=False, xlabel=False):
    sns.heatmap(data, ax=ax, cmap=cmap, cbar=cbar, annot=True, linewidths=0.5, fmt='d')
    
    # Retain the y-ticks when ylabel is True
    if ylabel:
        ax.set_yticklabels(ax.get_yticklabels(), rotation=0, fontsize=10)
    else:
        ax.set_ylabel("")
        ax.set_yticks([])  # Clear y-ticks if ylabel is not needed
        ax.set_yticklabels([])
    
    # Retain the x-ticks when xlabel is True
    if xlabel:
        ax.set_xticklabels(ax.get_xticklabels(), rotation=0, fontsize=10)
        ax.xaxis.set_label_position('top')
        ax.xaxis.tick_top()
    else:
        ax.set_xlabel("")
        ax.set_xticks([])  # Clear y-ticks if ylabel is not needed
        ax.set_xticklabels([])

    

# Plotting the heatmaps
plot_heatmap(human_A_subtable, axes[0, 0], cmap=oranges, ylabel=True, xlabel=True)  
plot_heatmap(mouse_A_subtable, axes[0, 1], cmap=oranges, xlabel=True)               
plot_heatmap(rat_A_subtable, axes[0, 2], cmap=oranges, xlabel=True)                 

plot_heatmap(human_B_subtable, axes[1, 0], cmap=greens, ylabel=True)               
plot_heatmap(mouse_B_subtable, axes[1, 1], cmap=greens)                            
plot_heatmap(rat_B_subtable, axes[1, 2], cmap=greens)    

# Adding labels for rows and columns
axes[0, 0].set_ylabel("Pathogen proteins\n", fontsize=12)
axes[1, 0].set_ylabel("Host proteins\n", fontsize=12)
axes[0, 0].set_xlabel("Human\n", fontsize=12)
axes[0, 1].set_xlabel("Mouse\n", fontsize=12)
axes[0, 2].set_xlabel("Rat\n", fontsize=12)


# Adding text to the plot
fig.text(0.5, 1, 'Mutations Localisation\n', ha='center', va='center', fontsize=14)
fig.text(0.0, 0.5, 'Mutations categories\n', ha='center', va='center', rotation='vertical', fontsize=14)

plt.subplots_adjust(hspace=0.1, wspace=0.2)

# Save the figure as a PNG file
plt.savefig('/home/bergogne/Documents/BactMentha_DB/03_Script/04_Website/static/stats/figures/figure_3.png', bbox_inches='tight', dpi=300)

# Adjust spacing
plt.tight_layout()
plt.show()
```

We can see on figure 3 that the majority of the mutations, upon the three taxa and both pathogen and host proteins, are found inside the binding regions or interfaces while there is a notable proportion of mutations for which the exact location on the protein is unknown. We can also see that those mutations are mainly linked to a decrease in the interaction length or strength independant of the taxon the proteins belong to. We cannot clearly define if some effects are associated more to the host proteins than to the pathogen proteins due to a lack of mutations data, even if the mutations in proteins of pathogens interacting with human proteins seem to be related more to the decrease of the interaction (strength/rate). 


# Annexe

:::{.center}
```{python}
#| echo: false

print("Bacteria-Human interactions pathogen proteins mutations\n")
print(human_tables['A'])
print("\n\nBacteria-Human interactions host proteins mutations\n")
print(human_tables['B'])
print("\n\nBacteria-Human interactions pathogen and host proteins mutations\n")
print(human_tables['A'])

print("\n\nBacteria-Mouse interactions pathogen proteins mutations\n")
print(mouse_tables['A'])
print("\n\nBacteria-Mouse interactions host proteins mutations\n")
print(mouse_tables['B'])
print("\n\nBacteria-Mouse interactions pathogen and host proteins mutations\n")
print(mouse_tables['A'])

print("\n\nBacteria-Rat interactions pathogen proteins mutations\n")
print(rat_tables['A'])
print("\n\nBacteria-Rat interactions host proteins mutations\n")
print(rat_tables['B'])
print("\n\nBacteria-Rat interactions pathogen and host proteins mutations\n")
print(rat_tables['A'])

```

