

user                       nginx;
worker_processes           1;

error_log                  /var/log/nginx/error.log warn;
pid                        /var/run/nginx.pid;

events {
    worker_connections     1024;
}

http {
    include                /etc/nginx/mime.types;
    default_type           application/octet-stream;
    
    log_format             main  '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';
    access_log             /var/log/nginx/access.log main;
    
    sendfile               on;
    keepalive_timeout      65;
    server_tokens          off;

    server {
        listen       666;
        server_name  localhost;

        location / {
            root           /usr/share/nginx/html;
            index          index.php index.html index.htm bactmentha_home.php;
        }

        # redirection de pages php -> short_url
        location /Home {
            rewrite ^/Home$ /bactmentha_home.php last;
        }
        location /Browse {
            rewrite ^/Browse$ /bactmentha_data.php last;
        }
        location /Download {
            rewrite ^/Download$ /bactmentha_download.php last;
        }
        location /Statistics {
            rewrite ^/Statistics$ /bactmentha_stats.php last;
        }
        location /FAQ {
            rewrite ^/FAQ$ /bactmentha_faq.php last;
        }
        location /Documentation {
            rewrite ^/Documentation$ /bactmentha_doc.php last;
        }
        location /Contact {
            rewrite ^/Contact$ /bactmentha_contact.php last;
        }
        location /Search {
            rewrite ^/Search$ /bactmentha_advSearch.php last;
        }

        location /home/bactmentha_archives/ {
            alias /home/bactmentha_archives/;
            try_files $uri $uri/ =404;
        }
        
            location /tmp/bactmentha_download/ {
            alias /tmp/bactmentha_download/;
            try_files $uri $uri/ =404;
        }


        location ~ \.php$ {
            root           /usr/share/nginx/html;
            include        fastcgi_params;
            fastcgi_pass   bactmentha_php:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  /script/$fastcgi_script_name;
            fastcgi_read_timeout 3600; # Set the read timeout to 1 hour
        }
        
        error_page         500 502 503 504 /50x.html;
        location = /50x.html {
            root           /usr/share/nginx/html;
        }
        
        # Adjust the maximum allowed size of the client request body
        client_max_body_size 100g; # Set to 100Gb


    }
}








