# -*- coding: utf-8 -*-

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $container_id
# docker-compose images
# docker-compose logs --tail 20 repo_name


################################
########### SERVICES ###########
################################
services:

#===================================
#===== -1- THE DATABASE SERVER =====
#===================================
  db: # name of the database service that will be used as host i the python scripts
    container_name: bactmentha_postgres 
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=$${POSTGRES_PASSWORD}
      - POSTGRES_DB=$${POSTGRES_DB}
      - POSTGRES_USER=$${POSTGRES_USER}
      - DATABASE_FOLDER_PATH=$${DATABASE_FOLDER_PATH}
      #- DB_PORTS=$${DB_PORTS} # This must be the same name that in the docker-compose.yml file
    ports:    # Set up ports exposed for other containers to connect to # - /etc/passwd:/etc/passwd:ro
      - 5433:5432
    volumes:
      - "${DATABASE_FOLDER_PATH}:/var/lib/postgresql/data"
    networks:
      - app-tier

#===================================
#=========== -2- PYTHON ============
#===================================
  app:
    container_name: bactmentha_python3
    image: bactmentha_python3
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=$${POSTGRES_PASSWORD}
      - POSTGRES_DB=$${POSTGRES_DB}
      - POSTGRES_USER=$${POSTGRES_USER}
      - CREATEDB_SCRIPT=$${CREATEDB_SCRIPT}
      - INSERTDATA_SCRIPT=$${INSERTDATA_SCRIPT}
      - UPDATEDB_SCRIPT=$${UPDATEDB_SCRIPT}
      - CREATEDB_PATH=$${CREATEDB_PATH}
      - INSERTDATA_PATH=$${INSERTDATA_PATH}
      - REFERENCE_PATH=$${REFERENCE_PATH}
      - ARCHIVE_PATH=$${ARCHIVE_PATH}
      - PROJECT_PATH=$${PROJECT_PATH}
      - COMMAND=$${COMMAND}
    depends_on:
      - db
    volumes:
      - "${PROJECT_PATH}:/BactMentha"
    command: >
      bash -c "
        case \$COMMAND in
          1)
            python3 \${CREATEDB_SCRIPT} --dbn=\${POSTGRES_DB} --dbh='db' --dbu=\${POSTGRES_USER} --dbpw=\${POSTGRES_PASSWORD} --dbpt='5432'
            ;;
          2)
            python3 ${INSERTDATA_SCRIPT} --dbn=${POSTGRES_DB} --dbh='db' --dbu=${POSTGRES_USER} --dbpw=${POSTGRES_PASSWORD} --dbpt='5432' --refpath=${REFERENCE_PATH} --cdbpath=${CREATEDB_PATH} --whopath=\${WHO_ANNOTATIONS_PATH}
            ;;
          3)
            python3 \${UPDATEDB_SCRIPT} --dbn=\${POSTGRES_DB} --dbh='db' --dbu=\${POSTGRES_USER} --dbpw=\${POSTGRES_PASSWORD} --dbpt='5432' --refpath=\${REFERENCE_PATH} --arcpath=\${ARCHIVE_PATH} --cdbpath=\${CREATEDB_PATH} --idbpath=\${INSERTDATA_PATH} --whopath=\${WHO_ANNOTATIONS_PATH}
            ;;
          *)
            echo 'No command specified or invalid command. Stoping bactmentha_python3 container.'
            ;;
        esac
      "
    networks:
      - app-tier

#===================================
#===== -3- ADMINER DB MANAGER ======
#===================================
  adminer:
    container_name: bactmentha_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-tier

#===================================
#====== -4- NGINX WEB SERVER =======
#===================================
  bactmentha_nginx:
    image: nginx
    container_name: bactmentha_nginx
    restart: unless-stopped
    ports:
      - 666:666
    environment:
      - WEBSITE_FOLDER_PATH=${WEBSITE_FOLDER_PATH}
      - NGINX_CONF_PATH=${NGINX_CONF_PATH}
    volumes:
      - "${WEBSITE_FOLDER_PATH}:/usr/share/nginx/html/"
      - "${NGINX_CONF_PATH}:/etc/nginx/nginx.conf"
      - "${PHP_ARCHIVE_PATH}:/home/bactmentha_archives"
      - "${PHP_DOWNLOAD_PATH}:/tmp/bactmentha_download"
    command: >
      bash -c "
        chmod -R 777 /tmp/bactmentha_download &&
        nginx -g 'daemon off;'
      "
    networks:
      - app-tier
    depends_on: 
      - bactmentha_php
      - db

#===================================
#============ -5- PHP ==============
#===================================
  bactmentha_php:
    image: bactmentha_php
    container_name: bactmentha_php
    restart: unless-stopped
    ports:
      - 9000:9000
    environment:
      - PHP_WEBSITE_FOLDER_PATH=${PHP_WEBSITE_FOLDER_PATH}
      - DATABASE_FOLDER_PATH=${DATABASE_FOLDER_PATH}
      - PHP_ARCHIVE_PATH=${PHP_ARCHIVE_PATH}
      - PHP_DOWNLOAD_PATH=${PHP_DOWNLOAD_PATH}
    volumes:
      - "${PHP_WEBSITE_FOLDER_PATH}:/script"
      - "${DATABASE_FOLDER_PATH}:/home/psql_database"
      - "${PHP_ARCHIVE_PATH}:/home/bactmentha_archives"
      - "${PHP_DOWNLOAD_PATH}:/tmp/bactmentha_download"
    networks:
      - app-tier
    depends_on:
        - db

################################
########### NETWORKS ###########
################################
networks:
  app-tier:
    driver: bridge


